%YAML:1.0

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 640
LEFT.width: 480
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data:[0.0, 0.0, 0.0, 0.0, 0.0]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [532.048, 0.0, 234.392, 0.0, 531.985, 304.082, 0.0, 0.0, 1.0]
LEFT.R:  !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [
          0.03282574, 0.0239244, 0.99917471, 0.00033084,
          0.99941041, 0.00928218, -0.03305573, -0.00049888, 
          -0.01006536, 0.99967068, -0.0236056, -0.00042663,
          0.0, 0.0, 0.0, 1.0
         ]

RIGHT.height: 640
RIGHT.width: 480
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data:[-0.0, 0.0, 0.0, 0.0, 0.0]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [531.588, 0.0, 241.429, 0.0, 531.740, 311.896, 0.0, 0.0, 1]
RIGHT.R:  !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [
          0.01114495, 0.00818984, 0.99990435, 0.0005275,
          0.99937759, 0.03337953, -0.01141248, 0.058505,
          -0.0334698, 0.99940919, -0.00781273, -0.00169502,
          0.0, 0.0, 0.0, 1.0
         ]
